### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by dungwinux**
To quickly build, simply use `make`

### CODE REVIEW

**Comment by NOVAglow** [comment]
This thing definitely helps since Khoa won't provide binaries for other OS rather than DOS and Windows.

**Comment by dungwinux** [comment]
This can solve your compiling problem, @taptapking

**Comment by NOVAglow** [comment]
He doesn't see it as a problem, @dungwinux.

**Comment by NOVAglow** [comment]
This is depended on `fpc`. Still would be better if @taptapking provided the binaries for all major operating systems.

**Pull request merged**
